### ISSUE TITLE
Create style guide

### ISSUE THREAD

**Issue by jmakeig** [jmakeig/pulchritude#1]
* Fonts
* Colors
* Padding, spacing
* etc.

**Comment by heymattallen** [comment]
what's the best format for this? I can take our style guide and lessons learned about the best way to show code in PPT and provide some guidelines. Do we also need the CSS?

[Branding-Guide.pdf](https://github.com/jmakeig/pulchritude/files/586290/Branding-Guide.pdf)

**Comment by jmakeig** [comment]
We need to define specific colors that map to the various aspects of the code, like key word or variable. pygments, the Python library I used in my proof-of-concept, defines the categories, we'd have to assign colors. And then there's the overall aesthetics, like font, line height, etc.

**Comment by jmakeig** [comment]
@heymattallen I’ve got an initial version working on my machine. I think it’s now just a matter of [filling in the colors](https://github.com/jmakeig/pulchritude/blob/master/marklogicstyle/style.py#L36-L81) and figuring out how to package it for distribution, especially Windows (#4).

**Comment by jmakeig** [comment]
Decision from Marketing (@stephen-gehring-ml) is to use the colors/fonts/layout that exists in Query Console today. In a future release, if we ref Query Console, this should follow as well.

**Comment by jmakeig** [comment]
From CodeMirror defaults:

```css
.cm-s-default .cm-keyword {color: #708;}
.cm-s-default .cm-atom {color: #219;}
.cm-s-default .cm-number {color: #164;}
.cm-s-default .cm-def {color: #00f;}
.cm-s-default .cm-variable,
.cm-s-default .cm-variable-2,
.cm-s-default .cm-variable-3,
.cm-s-default .cm-punctuation,
.cm-s-default .cm-property,
.cm-s-default .cm-operator {color: #099;}
.cm-s-default .cm-comment {color: #a50;}
.cm-s-default .cm-string {color: #a11;}
.cm-s-default .cm-string-2 {color: #f50;}
.cm-s-default .cm-meta {color: #555;}
.cm-s-default .cm-qualifier {color: #555;}
.cm-s-default .cm-builtin {color: #099;}
.cm-s-default .cm-bracket {color: #997;}
.cm-s-default .cm-tag {color: #170;}
.cm-s-default .cm-attribute {color: #00c;}
.cm-s-default .cm-hr {color: #999;}
.cm-s-default .cm-link {color: #00c;}

.cm-s-default .cm-error {color: #f00;}
.cm-invalidchar {color: #f00;}
```
